# Dockerfile.base
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    libgtk-3-dev \
    libboost-all-dev \
    libopenblas-dev \
    liblapack-dev \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
 && ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so.62.1.0 /usr/lib/x86_64-linux-gnu/libjpeg.so.8 \
    && rm -rf /var/lib/apt/lists/*